ExtDirectBundle_api:
    pattern:  /api.js
    defaults: { _controller: ExtDirectBundle:Direct:getApi }

ExtDirectBundle_route:
    pattern: /route
    defaults: { _controller: ExtDirectBundle:Direct:route }
