services:
    ext_direct.controller_resolver:
        class: Ext\DirectBundle\Router\ControllerResolver
        arguments: [ @service_container, @controller_name_converter, @ext_direct.route.collection, @monolog.logger.request ]
        
    ext_direct:
        class: Ext\DirectBundle\Response\ResponseFactory
        scope: request
        arguments: [ @request, @ext_direct.controller_resolver, @event_dispatcher, @templating ]

    ext_direct_test_service:
        class: Ext\DirectBundle\Controller\TestController
        arguments: [ @service_container ]

    ext_direct.route.collection:
        class: Ext\DirectBundle\Router\RouteCollection

    ext_direct.file.loader:
        class: Ext\DirectBundle\Router\Loader\FileLoader
        arguments: [ @file_locator ]

    ext_direct.yml.loader:
        class: Ext\DirectBundle\Router\Loader\YamlLoader
        arguments: [ @ext_direct.route.collection ]
        tags:
            - { name: ext_direct.loader }

    ext_direct.annotation_file.loader:
        class: Ext\DirectBundle\Router\Loader\AnnotationFileLoader
        arguments: [ @ext_direct.annotation_class.loader ]
        tags:
            - { name: ext_direct.loader }

    ext_direct.annotation_class.loader:
        class: Ext\DirectBundle\Router\Loader\AnnotationClassLoader
        arguments: [ @ext_direct.route.collection, @annotation_reader, @ext_direct.controller_resolver ]

    ext_direct.api:
        class: Ext\DirectBundle\Api\Api
        arguments: [ @ext_direct.route.collection, @router ]

    ext_direct.request_dispatcher:
        class: Ext\DirectBundle\Request\RequestDispatcher
        arguments: [ @ext_direct.controller_resolver, %kernel.debug% ]
